spring:
  application:
    name: StringManipulation
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/SMDb
    username: root
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

    
    hibernate:
      ddl-auto: update