spring:
  application:
    name: StringManipulation
    
  datasource:
    url: jdbc:mysql://localhost:3306/SMDb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

